title: Mani Bansal # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Software Engineer
  <br><br>
  <a href="mailto:manibansal2040@gmail.com">manibansal2040@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/mani-bansal-915aa8109/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/ManiBansal786/">Github</a> 
  <br>
  <br>
theme: jekyll-theme-minimal
